### ISSUE TITLE
Lock/Unlock of boxes with cryptography

### ISSUE THREAD

**Issue by albero94** [albero94/gw-blockchain-cardboard-killers#15]
•	Only authorized users can access the container
•	Non deniable, register who opened it
•	Record opening and closing actions
•	Include pictures?

**Comment by swilliams9671** [comment]
In order to lock and unlock the container, client identification and authentication of a user will need to occur. This can be done utilizing a PKI Smart Card (in addition to a username / password). This PKI Smart Card will provide identification and authentication using the digital signature. If the signature is valid, then the system has assurance that the user is in fact the identity asserted by the certificate. This will allow an authorized member of the supply chain process to open and close the container. As the “state” of the container changes (in this case opened or closed), the state is then posted to the Blockchain and signed with the user’s digital certificate. Other changes in state, such as temperature, can also be posted with PKI associated or assigned to the sensor. This provides data integrity of the transaction and all subsequent transactions on the Blockchain. Additionally, utilizing the PKI Smart Card will allow the user to encrypt and decrypt data as it is stored in the system and also in transit via secure connections (TLS). 
 
Should the pictures / video be taken manually by a person using a device or automatically inside the container using a camera / video there?
